{"name": "test_calc_minus", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == -1\n +  where 1 = <bound method Calc.calc_div of <Calc.Calc object at 0x11011bbb0>>()\n +    where <bound method Calc.calc_div of <Calc.Calc object at 0x11011bbb0>> = <Calc.Calc object at 0x11011bbb0>.calc_div", "trace": "self = <TestCalc.TestCalcDiv object at 0x11011b700>\n\n    def test_calc_minus(self):\n        div = Calc(-1, -1)\n>       assert div.calc_div() == -1\nE       assert 1 == -1\nE        +  where 1 = <bound method Calc.calc_div of <Calc.Calc object at 0x11011bbb0>>()\nE        +    where <bound method Calc.calc_div of <Calc.Calc object at 0x11011bbb0>> = <Calc.Calc object at 0x11011bbb0>.calc_div\n\nTestCalc.py:25: AssertionError"}, "start": 1589025806321, "stop": 1589025806321, "uuid": "cb4eabf3-4ed2-4e1b-8272-852ffff27503", "historyId": "bfa1b3b4271a26d9dbd874b820014960", "testCaseId": "acd21c4ae7d316e9c3d44b3beccf1967", "fullName": "TestCalc.TestCalcDiv#test_calc_minus", "labels": [{"name": "suite", "value": "TestCalc"}, {"name": "subSuite", "value": "TestCalcDiv"}, {"name": "host", "value": "cpe-172-100-1-147.twcny.res.rr.com"}, {"name": "thread", "value": "5921-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCalc"}]}